protected/modules/admin/controllers/PlayerController.php
<?php

class PlayerController extends AdminController {
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
//	public $layout='//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow',
                'actions' => array('index', 'add', 'addInjured', 'addSuspended', 'cancelDelist', 'cancelList',
                    'delete', 'delist', 'delisted', 'edit', 'injured', 'list', 'listed', 'removeInjured', 'removeSuspended', 'suspended', 'upload', 'uploadIS'),
                'expression' => 'User::hasRole(AdminRole::ADMIN | AdminRole::OPERATOR)',
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Lists all unlisted players
     */
    public function actionIndex() {
        _cs()->registerCoreScript('jquery.ui');
        AdminUtils::registerAdminJsFile('upload');
        AdminUtils::registerAdminCssFile('jui/base/jquery-ui');

        $players = new Player('searchIndex');

        if (isset($_GET['Player']))
            $players->attributes = $_GET['Player'];

        $this->render('index', array(
            'players' => $players,
        ));
    }

    /**
     * Lists all listed players
     */
    public function actionListed() {


        $players = new Player('searchListed');

        if (isset($_GET['Player']))
            $players->attributes = $_GET['Player'];

        $this->render('listed', array(
            'players' => $players,
        ));
    }

    /**
     * Lists all delisted players
     */
    public function actionDelisted() {


        $players = new Player('searchDelisted');

        if (isset($_GET['Player']))
            $players->attributes = $_GET['Player'];

        $this->render('delisted', array(
            'players' => $players,
        ));
    }

    /**
     * Lists all injured players
     */
    public function actionInjured() {
        _cs()->registerCoreScript('jquery.ui');
        AdminUtils::registerAdminJsFile('upload');
        AdminUtils::registerAdminCssFile('jui/base/jquery-ui');

        $players = new Player('search');
        $players->is_injured = true;

        if (isset($_GET['Player']))
            $players->attributes = $_GET['Player'];

        $this->render('injured', array(
            'players' => $players,
        ));
    }

    /**
     * Lists all suspended players
     */
    public function actionSuspended() {
        _cs()->registerCoreScript('jquery.ui');
        AdminUtils::registerAdminJsFile('upload');
        AdminUtils::registerAdminCssFile('jui/base/jquery-ui');

        $players = new Player('searchSuspended');
        $players->is_suspended = true;

        if (isset($_GET['Player']))
            $players->attributes = $_GET['Player'];

        $this->render('suspended', array(
            'players' => $players,
        ));
    }

    /**
     * Adds a new player
     */
    public function actionAdd() {
        $player = new Player;

        if (isset($_POST['Player'])) {
            $t = _app()->db->beginTransaction();
            try {

                $player->attributes = $_POST['Player'];
                if (!$player->save())
                    throw new Exception('Could not save player');

                $t->commit();
                $this->redirect(AdminUtils::aUrl('player/index'));
                _app()->end();
            } catch (Exception $e) {
                error_log($e);
                $t->rollback();
            }
        }

        $this->render('add', array(
            'player' => $player, 'src' => 'index'
        ));
    }

    /**
     * Edit a player's attributes
     * @param integer $id
     * @param string $src The page that called the action
     */
    public function actionEdit($id, $src='index') {
        $player = $this->loadModel($id);

        if (isset($_POST['Player'])) {
            $t = _app()->db->beginTransaction();
            try {

                $player->attributes = $_POST['Player'];
                if (!$player->save())
                    throw new Exception('Could not save player');

                $t->commit();
                $this->redirect(array($src));
            } catch (Exception $e) {
                error_log($e);
                $t->rollback();
            }
        }
        $this->render('edit', array(
            'player' => $player, 'src' => $src
        ));
    }

    /**
     * List a player by giving values
     */
    public function actionList() {
        AdminUtils::registerAdminJsFile('jquery.numeric');

        $player = '';
        $gc = Gameconfiguration::model()->find();
        if (isset($_POST['player'])) {
            $player = $this->loadModel($_POST['player']);
            $t = _app()->db->beginTransaction();
            try {
                if (time($_POST['list_date']) < time() || $_POST['list_date'] == null)
                    throw new Exception('List date must be in the future');
                if ($_POST['initial_value'] < $gc->overall_min_price_per_share || $_POST['initial_value'] > $gc->overall_max_price_per_share)
                    throw new Exception("Stock value for player must be between {$gc->overall_min_price_per_share} and {$gc->overall_max_price_per_share}");
                $player->list_date = $_POST['list_date'];
                $player->initial_value = $_POST['initial_value'];
                $player->current_value = $_POST['initial_value'];
                $player->bank_shares = $gc->total_shares_per_player;
                $player->total_points = 0;
                $player->vmi_season = 0;
                if (!$player->save())
                    throw new Exception('Could not save player');

                $t->commit();
                $this->redirect(AdminUtils::aUrl('player/index'));
                _app()->end();
            } catch (Exception $e) {
                error_log($e);
                _user()->setFlash('failure', $e->getMessage());
                $t->rollback();
            }
        }
        if (isset($_GET['id']))
            $player = $this->loadModel($_GET['id'])->id;
        $this->render('list', array('player' => $player, 'shares' => $gc->total_shares_per_player));
    }

    /**
     * Delist player
     * @param integer $id 
     */
    public function actionDelist($id) {
        _cs()->registerCoreScript('jquery.ui');
        AdminUtils::registerAdminJsFile('delist');
        AdminUtils::registerAdminCssFile('jui/base/jquery-ui');

        $player = $this->loadModel($id);

        if (isset($_POST['Player'])) {
            $t = _app()->db->beginTransaction();
            try {
                $gc = Gameconfiguration::model()->find();
                $player->attributes = $_POST['Player'];
                $player->delist_date = _app()->localtime->getLocalNow('Y-m-d H:i:s');
                if (isset($_POST['Player']['deleteTeam']))
                    $player->team_id = null;
                if (!$player->save())
                    throw new Exception('Could not delist player');

                $t->commit();
                $this->redirect(AdminUtils::aUrl('player/listed'));
                _app()->end();
            } catch (Exception $e) {
                error_log($e);
                $t->rollback();
            }
        }

        $this->render('delist', array('player' => $player));
    }

    /**
     * Cancel a scheduled delisted player
     * @param integer $id 
     */
    public function actionCancelDelist($id) {
        $player = $this->loadModel($id);

        $t = _app()->db->beginTransaction();
        try {
            $player->delist_date = null;
            if (!$player->save())
                throw new Exception('Could not delist player');

            $t->commit();
            $this->redirect(AdminUtils::aUrl('player/listed'));
            _app()->end();
        } catch (Exception $e) {
            error_log($e);
            $t->rollback();
        }
        $this->actionListed();
    }

    /**
     * Cancel a scheduled listed player
     * @param integer $id 
     */
    public function actionCancelList($id) {
        $player = $this->loadModel($id);

        $t = _app()->db->beginTransaction();
        try {
            $player->list_date = null;
            if (!$player->save())
                throw new Exception('Could not delist player');

            $t->commit();
            $this->redirect(AdminUtils::aUrl('player/index'));
            _app()->end();
        } catch (Exception $e) {
            error_log($e);
            $t->rollback();
        }
        $this->actionIndex();
    }

    /**
     * Add an injured player to the list
     */
    public function actionAddInjured() {
        $player = $this->loadModel($_POST['player']);

        $t = _app()->db->beginTransaction();
        try {
            $player->is_injured = true;
            if (!$player->save())
                throw new Exception('Could not add injured player');

            $t->commit();
            $this->redirect(AdminUtils::aUrl('player/injured'));
            _app()->end();
        } catch (Exception $e) {
            error_log($e);
            $t->rollback();
        }
        $this->actionInjured();
    }

    /**
     * Remove a player from the injured list
     * @param integer $id 
     */
    public function actionRemoveInjured($id) {
        $player = $this->loadModel($id);

        $t = _app()->db->beginTransaction();
        try {
            $player->is_injured = false;

protected/modules/admin/views/player/_delistForm.php
<div class="form">
    <?php
    $form = $this->beginWidget('CActiveForm', array(
            'id' => 'delist-form',
            'enableAjaxValidation' => false, 
            'enableClientValidation' => true,
        ));
    ?>

    <div class="row">
        <?php echo $player->shortname; ?>
    </div>
    
    <div class="row">
        <?php echo CHtml::hiddenField('Player[id]',$player->id); ?>
    </div>

    <div class="row">
        <?php echo CHtml::checkBox('Player[deleteTeam]', true); ?>
        <span style="font-weight: bold; font-size: 0.9em"><?php echo 'Remove his team (' . $player->team->name . ')'; ?></span>
    </div>

    <div class="row buttons">
    <?php echo CHtml::button('Delist now',array('id'=>'submitBtn')); ?>
        <?php echo CHtml::link('Cancel',AdminUtils::aUrl('player/listed')); ?>
    </div>

<?php $this->endWidget(); ?>
</div>
<div id="dialog"><?php echo $player->shortname; ?> will be delisted from the stockmarket from now on.Are you sure?</div>

protected/modules/admin/views/player/_form.php
<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'player-form',
	'enableAjaxValidation'=>false,'enableClientValidation'=>true,
)); ?>

    <div class="row">
        <?php echo $form->labelEx($player,'name'); ?>
        <?php echo $form->textField($player,'name'); ?>
        <?php echo $form->error($player,'name'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($player,'shortname'); ?>
        <?php echo $form->textField($player,'shortname'); ?>
        <?php echo $form->error($player,'shortname'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($player,'basicPosition'); ?>
        <?php echo $form->dropDownList($player,'basic_position_id',$this->getBasicPositions()); ?>
        <?php echo $form->error($player,'basicPosition'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($player,'team_id'); ?>
        <?php echo $form->dropDownList($player,'team_id',$this->getTeams(),array('prompt'=>'-')); ?>
        <?php echo $form->error($player,'team_id'); ?>
    </div>
    
    <div class="row">
        <?php echo $form->labelEx($player,'xml_id'); ?>
        <?php echo $form->textField($player,'xml_id'); ?>
        <?php echo $form->error($player,'xml_id'); ?>
    </div>

    <?php echo isset($src) ? CHtml::hiddenField('src',$src) : ''; ?>

    <div class="row buttons">
        <?php echo CHtml::submitButton('Save'); ?>
        <?php echo CHtml::link('Cancel',AdminUtils::aUrl("player/$src")); ?>
    </div>

<?php $this->endWidget(); ?>
</div>

protected/modules/admin/views/player/_listForm.php
<div class="stables"><span><?php echo _user()->hasFlash('failure') ? _user()->getFlash('failure') : ''; ?></span></div>
<div class="form">
<?php echo CHtml::form(AdminUtils::aUrl('player/list'),'post'); ?>

    <div class="row">
        <?php echo CHtml::label('Player to be listed','player'); ?>
        <?php echo CHtml::dropDownList('player',$player,$this->getNewPlayers()); ?>
    </div>

    <div class="row">
        <?php echo CHtml::label('List Date/Time','list_date'); ?>
        <?php
        $this->widget('zii.widgets.jui.CJuiDatePicker',array(
            'name'=>'list_date',
            'options'=>array(
                'dateFormat'=>'yy-mm-dd',
                'changeMonth' => true,
                'changeYear' => true,
                'minDate' => date('Y-m-d',strtotime(date("Y-m-d", strtotime(date('Y-m-d'))) . " +1 day")),
                ),
            'htmlOptions'=>array('readonly'=>true),
            ));
        ?>
    </div>

    <div class="row">
        <?php echo CHtml::label('Initial Total Value','total_value'); ?>
        <?php echo CHtml::textField('total_value','',array('id'=>'total_value')); ?>
    </div>

    <div class="row">
        <?php echo CHtml::label('Number of Shares','bank_shares'); ?>
        <?php echo CHtml::textField('bank_shares',$shares,array('readonly'=>true,'id'=>'bank_shares')); ?>
    </div>

    <div class="row">
        <?php echo CHtml::label('Initial Price / Share','initial_value'); ?>
        <?php echo CHtml::textField('initial_value','',array('readonly'=>true,'id'=>'initial_value')); ?>
    </div>

    <div class="row buttons">
        <?php echo CHtml::submitButton('Save'); ?>
        <?php echo CHtml::link('Cancel',AdminUtils::aUrl('player/index')); ?>
    </div>

<?php echo CHtml::endForm(); ?>
</div>

<script type="text/javascript">
    $(document).ready(function(){
    $("#total_value").focusout(function(){
        var bs = $("#bank_shares").val();
        var tv = $(this).val();
        var init = tv/bs;
        $("#initial_value").val(init.toFixed(2)).change();
    });

    $("#total_value, #bank_shares").numeric();
});
</script>

protected/modules/admin/views/player/_upload.php
<?php
echo CHtml::form(AdminUtils::aUrl('player/upload'),'post',
                   array(
                    'enctype' => 'multipart/form-data',
                    ));
echo CHtml::fileField('xml');?>
<br /><br />
<?php
echo CHtml::submitButton('Upload');
echo CHtml::endForm();
?>

protected/modules/admin/views/player/_uploadIS.php
<?php
echo CHtml::form(AdminUtils::aUrl('player/uploadIS'),'post',
                   array(
                    'enctype' => 'multipart/form-data',
                    ));
echo CHtml::fileField('xml');?>
<br /><br />
<?php
echo CHtml::submitButton('Upload');
echo CHtml::endForm();
?>

protected/modules/admin/views/player/add.php
<?php
$this->renderPartial('_form',array('player'=>$player,'src'=>$src));
?>

protected/modules/admin/views/player/delist.php
<?php
$this->renderPartial('_delistForm',array('player'=>$player));
?>

protected/modules/admin/views/player/delisted.php
<?php
$this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'delisted',
    'dataProvider' => $players->searchDelisted(),
    'filter' => $players,
    'pager' => array('class' => 'CLinkPager', 'header' => ''),    'columns' => array(
        array(
            'header' => '',
            'value' => '$this->grid->dataProvider->pagination->currentPage*$this->grid->dataProvider->pagination->pageSize + $row+1',
        ),
        array(
            'name' => 'name'
        ),
        array(
            'name' => 'delist_date',
            'value' => 'Utils::date($data->delist_date)',
            'filter' => false,
            'htmlOptions' => array('class' => 'tcenter')
        ),
        array(
            'name' => 'basic_position_id',
            'value' => '$data->basicPosition->abbreviation',
            'filter' => CHtml::listData(BasicPosition::model()->findAll(), 'id', 'abbreviation'),
            'htmlOptions' => array('class' => 'tcenter')
        ),
        array(
            'name' => 'team_id',
            'value' => '$data->team != null ? $data->team->shortname5 : ""',
            'filter' => CHtml::listData(Team::model()->findAll(), 'id', 'shortname5'),
            'htmlOptions' => array('class' => 'tcenter')
        ),
        array(
            'class' => 'CButtonColumn',
            'template' => '{update}',
            'updateButtonImageUrl' => AdminUtils::adminImageUrl('edit.png'),
            'updateButtonUrl' => 'AdminUtils::aUrl("player/edit", array("id" => $data->id, "src" => "delisted"))',
        ),
    ),
));
?>

protected/modules/admin/views/player/edit.php
<?php
$this->renderPartial('_form',array('player'=>$player,'src'=>$src));
?>

protected/modules/admin/views/player/index.php
<a href="<?php echo AdminUtils::aUrl('player/add'); ?>"><div class="addButton">Add new player</div></a>
<span style="float: right"><a href="#" class="upload"><div class="addButton">Mass insert players (Upload XML)</div></a></span>
<br><br>
<div class="stables">
    <span class="success"><?php echo _user()->hasFlash('success') ? _user()->getFlash('success') : ''; ?></span>
    <span><?php echo _user()->hasFlash('failure') ? _user()->getFlash('failure') : ''; ?></span>
</div>

<?php
$this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'unlisted',
    'dataProvider' => $players->searchIndex(),
    'filter' => $players,
    'pager' => array('class' => 'CLinkPager', 'header' => ''),    'columns' => array(
        array(
            'header' => '',
            'value' => '$this->grid->dataProvider->pagination->currentPage*$this->grid->dataProvider->pagination->pageSize + $row+1',
        ),
        array(
            'name' => 'name'
        ),
        array(
            'name' => 'basic_position_id',
            'value' => '$data->basicPosition->abbreviation',
            'filter' => CHtml::listData(BasicPosition::model()->findAll(), 'id', 'abbreviation'),
            'htmlOptions' => array('class' => 'tcenter')
        ),
        array(
            'name' => 'team_id',
            'value' => '$data->team != null ? $data->team->shortname5 : ""',
            'filter' => CHtml::listData(Team::model()->findAll(), 'id', 'shortname5'),
            'htmlOptions' => array('class' => 'tcenter')
        ),
        array(
            'header' => '',
            'type' => 'raw',
            'value' => '$data->list_date == null ? CHtml::link("List",AdminUtils::aUrl("player/list",array("id"=>$data->id))) : "To be listed on: ".Utils::date($data->list_date)." at ".Utils::currency($data->initial_value)."/shr<br />".CHtml::link("Cancel",AdminUtils::aUrl("player/cancelList",array("id"=>$data->id)))',
            'filter' => false,
        ),
        array(
            'class' => 'CButtonColumn',
            'template' => '{update}{delete}',
            'updateButtonImageUrl' => AdminUtils::adminImageUrl('edit.png'),
            'deleteButtonImageUrl' => AdminUtils::adminImageUrl('delete.png'),
            'updateButtonUrl' => 'AdminUtils::aUrl("player/edit", array("id" => $data->id))',
            'deleteConfirmation'=>"Are you sure you wish to delete this player from the system?"
        ),
    ),
));
?>

<div id="uploadPop" style="display: none;">
    <?php $this->renderPartial('_upload'); ?>
</div>

protected/modules/admin/views/player/injured.php
<br />
<span style="float: right"><a href="#" class="upload"><div class="addButton">Update injured & suspended lists (Upload XML)</div></a></span>
<div class="stables">
    <span class="success"><?php echo _user()->hasFlash('success') ? _user()->getFlash('success') : ''; ?></span>
    <span><?php echo _user()->hasFlash('failure') ? _user()->getFlash('failure') : ''; ?></span>
</div>
<div class="form">
    <div class="row">
        <?php
        echo CHtml::form(AdminUtils::aUrl('player/addInjured'), 'post');
        echo CHtml::label('Add injured player', 'player');
        echo CHtml::dropDownList('player', '', $this->getUninjuredPlayers());
        echo CHtml::submitButton('Add');
        echo CHtml::endForm();
        ?>
    </div>
</div>
<?php
$this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'injured',
    'dataProvider' => $players->searchAdmin(),
    'filter' => $players,
    'pager' => array('class' => 'CLinkPager', 'header' => ''),    'columns' => array(
        array(
            'header' => '',
            'value' => '$this->grid->dataProvider->pagination->currentPage*$this->grid->dataProvider->pagination->pageSize + $row+1',
        ),
        array(
            'name' => 'name'
        ),
        array(
            'name' => 'pos',
            'value' => '$data->basicPosition->abbreviation',
            'filter' => false,
            'htmlOptions' => array('class' => 'tcenter')
        ),
        array(
            'name' => 'myTeam',
            'value' => '$data->team != null ? $data->team->shortname5 : "-"',
            'filter' => false,
            'htmlOptions' => array('class' => 'tcenter')
        ),
        array(
            'class' => 'CButtonColumn',
            'template' => '{delete}',
            'deleteButtonImageUrl' => AdminUtils::adminImageUrl('remove.png'),
            'deleteButtonUrl' => 'AdminUtils::aUrl("player/removeInjured", array("id" => $data->id))',
            'deleteConfirmation' => 'Are you sure you want to delete this player?',
            'deleteButtonLabel' => 'Remove',
        ),
    ),
));
?>

<div id="uploadPop" style="display: none;">
    <?php $this->renderPartial('_uploadIS'); ?>
</div>

protected/modules/admin/views/player/list.php
<?php
$this->renderPartial('_listForm',array('player'=>$player,'shares'=>$shares));
?>

protected/modules/admin/views/player/listed.php
<div class="stables">
    <span class="success"><?php echo _user()->hasFlash('success') ? _user()->getFlash('success') : ''; ?></span>
    <span><?php echo _user()->hasFlash('failure') ? _user()->getFlash('failure') : ''; ?></span>
</div>

<?php
$this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'listed',
    'dataProvider' => $players->searchListed(),
    'filter' => $players,
    'pager' => array('class' => 'CLinkPager', 'header' => ''),    'columns' => array(
        array(
            'header' => '',
            'value' => '$this->grid->dataProvider->pagination->currentPage*$this->grid->dataProvider->pagination->pageSize + $row+1',
        ),
        array(
            'name' => 'name'
        ),
        array(
            'name' => 'list_date',
            'value' => 'Utils::date($data->list_date)',
            'filter' => false,
            'htmlOptions' => array('class' => 'tcenter')
        ),
        array(
            'name' => 'initial_value',
            'value' => '_currency($data->initial_value)',
            'filter' => false,
            'htmlOptions' => array('class' => 'tright')
        ),
        array(
            'name' => 'basic_position_id',
            'value' => '$data->basicPosition->abbreviation',
            'filter' => CHtml::listData(BasicPosition::model()->findAll(), 'id', 'abbreviation'),
            'htmlOptions' => array('class' => 'tcenter')
        ),
        array(
            'name' => 'team_id',
            'value' => '$data->team != null ? $data->team->shortname5 : ""',
            'filter' => CHtml::listData(Team::model()->findAll(), 'id', 'shortname5'),
            'htmlOptions' => array('class' => 'tcenter')
        ),
        array(
            'header' => '',
            'type' => 'raw',
            'value' => '$data->delist_date == null ? CHtml::link("Delist",AdminUtils::aUrl("player/delist",array("id"=>$data->id))) : "To be delisted on: ".Utils::date($data->delist_date)."<br />".CHtml::link("Cancel",AdminUtils::aUrl("player/cancelDelist",array("id"=>$data->id)))',
            'filter' => false,
        ),
        array(
            'class' => 'CButtonColumn',
            'template' => '{update}',
            'updateButtonImageUrl' => AdminUtils::adminImageUrl('edit.png'),
            'updateButtonUrl' => 'AdminUtils::aUrl("player/edit", array("id" => $data->id, "src" => "listed"))',
        ),
    ),
));
?>

protected/modules/admin/views/player/suspended.php
<br />
<span style="float: right"><a href="#" class="upload"><div class="addButton">Update injured & suspended lists (Upload XML)</div></a></span>
<div class="form">
    <div class="row">
        <?php
        echo CHtml::form(AdminUtils::aUrl('player/addSuspended'), 'post');
        echo CHtml::label('Add suspended player', 'player');
        echo CHtml::dropDownList('player', '', $this->getUnsuspendedPlayers());
        echo CHtml::submitButton('Add');
        echo CHtml::endForm();
        ?>
    </div>
</div>
<?php
$this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'suspended',
    'dataProvider' => $players->searchAdmin(),
    'filter' => $players,
    'pager' => array('class' => 'CLinkPager', 'header' => ''),    'columns' => array(
        array(
            'header' => '',
            'value' => '$this->grid->dataProvider->pagination->currentPage*$this->grid->dataProvider->pagination->pageSize + $row+1',
        ),
        array(
            'name' => 'name'
        ),
        array(
            'name' => 'pos',
            'value' => '$data->basicPosition->abbreviation',
            'filter' => false,
            'htmlOptions' => array('class' => 'tcenter')
        ),
        array(
            'name' => 'myTeam',
            'value' => '$data->team != null ? $data->team->shortname5 : "-"',
            'filter' => false,
            'htmlOptions' => array('class' => 'tcenter')
        ),
        array(
            'class' => 'CButtonColumn',
            'template' => '{delete}',
            'deleteButtonImageUrl' => AdminUtils::adminImageUrl('remove.png'),
            'deleteButtonUrl' => 'AdminUtils::aUrl("player/removeSuspended", array("id" => $data->id))',
            'deleteConfirmation' => 'Are you sure you want to delete this player?',
            'deleteButtonLabel' => 'Remove',
        ),
    ),
));
?>

<div id="uploadPop" style="display: none;">
    <?php $this->renderPartial('_uploadIS'); ?>
</div>