protected/modules/admin/controllers/CmsController.php
<?php

class CmsController extends AdminController {
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
//	public $layout='//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow',
                'actions' => array('index', 'save', 'tips', 'addTip', 'delete', 'reportReasons', 'addReason', 'deleteReason'),
                'expression' => 'User::hasRole(AdminRole::ADMIN | AdminRole::OPERATOR)',
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        _cs()->registerCoreScript('jquery.ui');
        AdminUtils::registerAdminCssFile('jui/base/jquery-ui');

        $lang = isset($_POST['lang']) ? $_POST['lang'] : Language::model()->id(_app()->language);
        $sc = StaticContent::model()->findAll('lang = :lang', array(':lang' => $lang));
        $this->render('index', array('sc' => $sc, 'lang' => $lang));
    }

    /**
     * Saves all static content and redirects to static content editors
     */
    public function actionSave() {
        $vars = StaticContent::model()->findAll(array(
            'select' => 'section',
            'distinct' => true
            ));
        foreach ($vars as $var) {
            if (isset($_POST[$var->section]) && !is_null($_POST[$var->section])) {
                $sc = StaticContent::model()->find('lang = :lang AND section = :section', array(':lang' => $_POST['lang'], ':section' => $var->section));
                if ($var->section == 'TermsOfUse' && $sc->content != $_POST[$var->section]){
                    $managers = Manager::model()->findAll();
                    foreach ($managers as $manager) {
                        $manager->accepted_terms = false;
                        $manager->update();
                    }
                }
                $sc->content = $_POST[$var->section];
                $sc->save(true, array('content'));
            }
        }

        $this->redirect(AdminUtils::aUrl('cms/index'));
    }

    /**
     * Tips page
     */
    public function actionTips() {
        $tips = new Tips;

        $this->render('tips', array('tips' => $tips));
    }

    /**
     * Add a tip
     */
    public function actionAddTip() {
        $tip = new Tips;

        if (isset($_POST['Tips'])) {
            $tip->attributes = $_POST['Tips'];
            if ($tip->save())
                $this->redirect(AdminUtils::aUrl('cms/tips'));
            else
                error_log(Debug::arObjectErrors($tip));
        }

        $this->render('addTip', array('tip' => $tip));
    }

    public function actionDelete($id) {
        $tip = Tips::model()->findByPk($id);
        $tip->delete();

        $this->redirect(AdminUtils::aUrl('cms/index'));
    }

    public function actionReportReasons() {
        $reasons = new ReportReason;

        $this->render('reportReasons', array('reasons' => $reasons));
    }

    public function actionAddReason() {
        $reason = new ReportReason;
        $reasonTypes = ReportReason::getTypes();

        if (isset($_POST['ReportReason'])) {
            $reason->attributes = $_POST['ReportReason'];
            if ($reason->save()) {
                $this->redirect(AdminUtils::aUrl('cms/reportReasons'));
            }else
                error_log(Debug::arObjectErrors($reason));
        }

        $this->render('addReason', array('reason' => $reason, 'reasonTypes' => $reasonTypes));
    }

    public function actionDeleteReason($id) {
        ReportReason::model()->deleteByPk($id);

        $this->redirect(AdminUtils::aUrl('cms/reportReasons'));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer the ID of the model to be loaded
     */
    public function loadModel($id) {
        $model = Announcement::model()->findByPk((int) $id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

}

protected/modules/admin/views/cms/addReason.php
<div class="stables">
    <span><?php echo _user()->hasFlash('failure') ? _user()->getFlash('failure') : ''; ?>
</div>
<div class="form">
    <?php
    $form = $this->beginWidget('CActiveForm', array(
            'id' => 'reason-form',
            'enableAjaxValidation' => false, 'enableClientValidation' => true,
        ));
    ?>

    <div class="row">
        <?php echo $form->labelEx($reason, 'reason'); ?>
        <?php echo $form->textArea($reason, 'reason',array('cols'=>40,'rows'=>6)); ?>
        <?php echo $form->error($reason, 'reason'); ?>
    </div>
    
    <div class="row">
        <?php echo $form->labelEx($reason, 'reason_type'); ?>
        <?php echo $form->dropDownList($reason, 'reason_type', $reasonTypes); ?>
        <?php echo $form->error($reason, 'reason_type'); ?>
    </div>
    
    <div class="row">
        <?php echo $form->labelEx($reason, 'reportAction'); ?>
        <?php echo $form->listBox($reason, 'reportAction', CHtml::listData(ReportAction::model()->findAll(), 'id', 'action'),array('multiple' => 'multiple','size' => 6)); ?>
        <?php echo $form->error($reason, 'reportAction'); ?>
    </div>
    
    <div class="row">
        <?php echo $form->labelEx($reason, 'language_id'); ?>
        <?php echo $form->dropDownList($reason, 'language_id', CHtml::listData(Language::model()->findAll(), 'id', 'code')); ?>
        <?php echo $form->error($reason, 'language_id'); ?>
    </div>

    <div class="row buttons">
        <?php echo CHtml::submitButton('Save'); ?>
        <?php echo CHtml::link('Cancel',AdminUtils::aUrl('cms/reportReasons')); ?>
    </div>

    <?php $this->endWidget(); ?>
</div>

protected/modules/admin/views/cms/addTip.php
<div class="form">
    <?php
    $form = $this->beginWidget('CActiveForm', array(
            'id' => 'tip-form',
            'enableAjaxValidation' => false, 'enableClientValidation' => true,
        ));
    ?>

    <div class="row">
        <?php echo $form->labelEx($tip, 'tip'); ?>
        <?php echo $form->textArea($tip, 'tip',array('cols'=>40,'rows'=>6)); ?>
        <?php echo $form->error($tip, 'tip'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($tip, 'tip_group'); ?>
        <?php echo $form->dropDownList($tip, 'tip_group', array(1=>1,2=>2,3=>3)); ?>
        <?php echo $form->error($tip, 'tip_group'); ?>
    </div>
    
    <div class="row">
        <?php echo $form->labelEx($tip, 'lang'); ?>
        <?php echo $form->dropDownList($tip, 'lang', CHtml::listData(Language::model()->findAll(), 'id', 'code')); ?>
        <?php echo $form->error($tip, 'lang'); ?>
    </div>

    <div class="row buttons">
        <?php echo CHtml::submitButton('Save'); ?>
        <?php echo CHtml::link('Cancel',AdminUtils::aUrl('cms/tips')); ?>
    </div>

    <?php $this->endWidget(); ?>
</div>

protected/modules/admin/views/cms/index.php
<?php
echo CHtml::form(AdminUtils::aUrl('cms/index'));
echo CHtml::dropDownList('lang', $lang, CHtml::listData(Language::model()->findAll(), 'id', 'code'), array('submit' => ''));
echo CHtml::endForm();
?>
<div class="tabs">
    <ul>
        <?php foreach ($sc as $texts) : ?>
            <li><a href="#<?php echo $texts->id . $texts->lang; ?>"><?php echo $texts->section; ?></a></li>
        <?php endforeach; ?>
    </ul>
    <?php foreach ($sc as $text) : ?>
        <div id="<?php echo $text->id . $text->lang; ?>">
            <?php echo CHtml::form(AdminUtils::aUrl('cms/save')); ?>
            <div class="row">
                <?php if ($text->section == 'VideoUrl') : ?>
                    <em>http://www.youtube.com/watch?v=<?php echo CHtml::textField($text->section, $text->content); ?></em>
                <?php else : ?>
                    <?php
                    $this->widget('ext.editMe.ExtEditMe', array(
                        'name' => $text->section,
                        'value' => $text->content,
                        'htmlOptions' => array('option' => 'value'),
                        'toolbar' => array(
                            array('Undo', '-', 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat'),
                            array('NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', 'BidiLtr', 'BidiRtl'),
                            array('Link', 'Unlink', 'Anchor'),
                            array('Image', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe'),
                            '/',
                            array('Styles', 'Format', 'Font', 'FontSize'),
                            array('TextColor', 'BGColor'),
                        )
                    ));
                    ?>
                <?php endif; ?>
            </div>
            <?php echo CHtml::hiddenField('lang', $text->lang); ?>
            <div class="row buttons">
                <?php echo CHtml::submitButton('Save', array('id' => 'submitBtn')); ?>
            </div>
            <?php CHtml::endForm(); ?>
        </div>
    <?php endforeach; ?>
</div>

<script>
    $(function() {
        $( ".tabs" ).tabs();
    });
</script>

protected/modules/admin/views/cms/reportReasons.php
<a href="<?php echo AdminUtils::aUrl('cms/addReason'); ?>"><div class="addButton">Add new reason</div></a>
<br/>
<?php
$this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider' => $reasons->search(),    'columns' => array(
        array(
            'name' => 'reportActions',
            'value' =>'$data->getReportActions()',
            'htmlOptions'=>array('width'=>'15%','class'=>'tcenter')
        ),
        array(
            'name' => 'reason_type',
            'value' => 'ReportReason::getType($data->reason_type)',
            'htmlOptions'=>array('width'=>'15%')
        ),
        array(
            'name' => 'reason',
            'htmlOptions'=>array('width'=>'60%')
        ),
        array(
            'name' => 'language.code',
            'htmlOptions'=>array('width'=>'10%','class'=>'tcenter')
        ),
        array(
            'class' => 'CButtonColumn',
            'template' => '{delete}',
            'deleteButtonImageUrl' => AdminUtils::adminImageUrl('delete.png'),
            'deleteButtonUrl' =>' AdminUtils::aUrl("cms/deleteReason",array("id" => $data->id))',
            'deleteConfirmation' => "All reports for this reason will be deleted? Are you sure you want to delete this reason?",
        ),
    ),
));
?>

protected/modules/admin/views/cms/tips.php
<a href="<?php echo AdminUtils::aUrl('cms/addTip'); ?>"><div class="addButton">Add new tip</div></a>
<br/>
<?php
$this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider' => $tips->search(),    'columns' => array(
        array(
            'name' => 'tip_group',
            'htmlOptions'=>array('width'=>'10%','class'=>'tcenter')
        ),
        array(
            'name' => 'tip',
            'htmlOptions'=>array('width'=>'70%')
        ),
        array(
            'name' => 'lang0.code',
            'htmlOptions'=>array('width'=>'10%','class'=>'tcenter')
        ),
        array(
            'class' => 'CButtonColumn',
            'template' => '{delete}',
            'deleteButtonImageUrl' => AdminUtils::adminImageUrl('delete.png'),
        ),
    ),
));
?>