protected/modules/admin/controllers/ForumController.php
<?php

class ForumController extends AdminController {

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow',
                'expression' => 'User::hasRole(AdminRole::ADMIN | AdminRole::OPERATOR)',
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Lists all categories
     */
    public function actionIndex() {
        $categories = new Category('search');
        $this->render('index', array(
            'categories' => $categories,
            'maxRank' => Category::model()->getMaxRank(),
            'languages' => Language::model()->findAll(),
        ));
    }

    /**
     *
     * @param type $category
     */
    public function actionDiscussions($category) {
        $categoryModel = Category::model()->findByPk($category);
        if (!$categoryModel->text) {
            throw new CHttpException('404');
        }

        $discussions = new CategoryDiscussion('search');
        $discussions->category_id = $category;

        if (isset($_GET['CategoryDiscussion'])) {
            $discussions->attributes = $_GET['CategoryDiscussion'];
        }


        $this->render('discussions', array(
            'discussions' => $discussions,
            'category' => $categoryModel,
        ));
    }

    /**
     *
     * @param type $discussion
     */
    public function actionComments($discussion) {
        $category = CategoryDiscussion::model()->findByAttributes(array('discussion_id' => $discussion));
        if (!$category->category->text) {
            throw new CHttpException('404');
        }

        $comments = new Comment('searchAdmin');
        $comments->discussion_id = $discussion;

        if (isset($_GET['Comment'])) {
            $comments->attributes = $_GET['Comment'];
        }

        $this->render('comments', array(
            'category' => $category,
            'comments' => $comments
        ));
    }

    public function actionShow($discussion) {
        $comments = new Comment('searchAdmin');
        $comments->discussion_id = $discussion;

        if (isset($_GET['Comment'])) {
            $comments->attributes = $_GET['Comment'];
        }

        $this->render('show', array(
            'category' => CategoryDiscussion::model()->findByAttributes(array('discussion_id' => $discussion)),
            'comments' => $comments
        ));
    }

    /**
     *
     * @param type $id
     */
    public function actionUpdate($id) {
        $category = Category::model()->findByPk($id);
        if ($category->edit()) {
            $this->redirect(AdminUtils::aUrl('forum/index'));
        }
        $this->render('category', array(
            'action' => 'update',
            'category' => $category,
            'languages' => Language::model()->findAll()
        ));
    }

    /**
     *
     * @param type $id
     */
    public function actionDelete($id) {
        Category::model()->findByPk($id)->delete();
        $this->redirect(AdminUtils::aUrl('forum/index'));
    }

    /**
     *
     */
    public function actionAddCategory() {
        $category = new Category;
        if ($category->edit()) {
            $this->redirect(AdminUtils::aUrl('forum/index'));
        }
        $this->render('category', array(
            'action' => 'add',
            'category' => $category,
            'languages' => Language::model()->findAll(),
        ));
    }

    /**
     *
     * @param type $id
     */
    public function actionCategoryRankUp($id) {
        $category = Category::model()->findByPk($id);
        $category->updateRank(-1);
        $this->redirect(AdminUtils::aUrl('forum/index'));
    }

    /**
     *
     * @param type $id
     */
    public function actionCategoryRankDown($id) {
        $category = Category::model()->findByPk($id);
        $category->updateRank(1);
        $this->redirect(AdminUtils::aUrl('forum/index'));
    }

    /**
     *
     * @param type $id
     * @return type
     */
    public function actionOpenDiscussion($id) {
        if (!Utils::isAjax())
            return;

        $discussion = Discussion::model()->findByPk($id);
        $discussion->comments_open = true;
        if ($discussion->save(false, array('comments_open'))) {
            Utils::jsonReturn(array('success' => true));
        }

        Utils::jsonReturn(array('success' => false));
    }

    /**
     *
     * @param type $id
     * @return type
     */
    public function actionCloseDiscussion($id) {
        if (!Utils::isAjax())
            return;

        $discussion = Discussion::model()->findByPk($id);
        $discussion->comments_open = false;
        if ($discussion->save(false, array('comments_open'))) {
            Utils::jsonReturn(array('success' => true));
        }

        Utils::jsonReturn(array('success' => false));
    }

    /**
     *
     * @param type $id
     * @return type
     */
    public function actionDeleteDiscussion($id) {
        if (!Utils::isAjax())
            return;

        $discussion = Discussion::model()->findByPk($id);
        foreach ($discussion->comments as $comment)
            Report::model()->deleteReport(ReportReason::MESSAGE, $comment->commentor_id, $comment->id);
        if ($discussion->delete()) {
            Utils::jsonReturn(array('success' => true));
        }

        Utils::jsonReturn(array('success' => false));
    }

    /**
     *
     * @param type $id
     * @return type
     */
    public function actionHideComment($id) {
        if (!Utils::isAjax())
            return;

        $comment = Comment::model()->findByPk($id);
        $comment->visible = false;
        if ($comment->save(false, array('visible')))
            Utils::jsonReturn(array('success' => true));

        Utils::jsonReturn(array('success' => false));
    }

    /**
     *
     * @param type $id
     * @return type
     */
    public function actionShowComment($id) {
        if (!Utils::isAjax())
            return;

        $comment = Comment::model()->findByPk($id);
        $comment->visible = true;
        if ($comment->save(false, array('visible')))
            Utils::jsonReturn(array('success' => true));

        Utils::jsonReturn(array('success' => false));
    }

    /**
     *
     * @param type $id
     * @return type
     */
    public function actionHideDiscussion($id) {
        if (!Utils::isAjax())
            return;

        $discussion = Discussion::model()->findByPk($id);
        $discussion->visible = false;
        if ($discussion->save(false, array('visible')))
            Utils::jsonReturn(array('success' => true));

        Utils::jsonReturn(array('success' => false));
    }

    /**
     *
     * @param type $id
     * @return type
     */
    public function actionShowDiscussion($id) {
        if (!Utils::isAjax())
            return;

        $discussion = Discussion::model()->findByPk($id);
        $discussion->visible = true;
        if ($discussion->save(false, array('visible')))
            Utils::jsonReturn(array('success' => true));

        Utils::jsonReturn(array('success' => false));
    }

    /**
     *
     * @param type $id
     * @return type
     */
    public function actionDeleteComment($id) {
        if (!Utils::isAjax())
            return;

        $comment = Comment::model()->findByPk($id);
        if ($comment->delete())
            Utils::jsonReturn(array('success' => true));

        Utils::jsonReturn(array('success' => false));
    }

    /**
     *
     */
    public function actionMatches() {
        // Get all match discussions
        $discussions = new MatchDiscussion('search');

        if (isset($_GET['MatchDiscussion'])) {
            $discussions->attributes = $_GET['MatchDiscussion'];
        }

        $this->render('matches', array('discussions' => $discussions));
    }

    /**
     *
     * @param type $discussion
     */
    public function actionMatch($discussion) {
        $comments = new Comment('searchAdmin');
        $comments->discussion_id = $discussion;

        if (isset($_GET['Comment'])) {
            $comments->attributes = $_GET['Comment'];
        }

        $this->render('match', array(
            'game' => MatchDiscussion::model()->findByAttributes(array('discussion_id' => $discussion))->game,
            'comments' => $comments
        ));
    }

    /**
     *
     */
    public function actionLeagues() {
        $discussions = new CustomLeagueDiscussion('searchExceptFanLeagues');

        if (isset($_GET['CustomLeagueDiscussion'])) {
            $discussions->attributes = $_GET['CustomLeagueDiscussion'];
        }

        $this->render('leagues', array('discussions' => $discussions));
    }

    /**
     *
     */
    public function actionFanLeagues() {
        $discussions = new CustomLeagueDiscussion('searchFanLeagues');

        if (isset($_GET['CustomLeagueDiscussion'])) {
            $discussions->attributes = $_GET['CustomLeagueDiscussion'];
        }

        $this->render('fanLeagues', array('discussions' => $discussions));
    }

    /**
     *
     * @param type $discussion
     */
    public function actionLeague($discussion) {
        $comments = new Comment('searchAdmin');
        $comments->discussion_id = $discussion;

        if (isset($_GET['Comment'])) {
            $comments->attributes = $_GET['Comment'];
        }

        $this->render('league', array(
            'league' => CustomLeagueDiscussion::model()->findByAttributes(array('discussion_id' => $discussion))->league,
            'comments' => $comments
        ));
    }

}

protected/modules/admin/controllers/ReportController.php
<?php

class ReportController extends AdminController {
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
//	public $layout='//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'users' => array('@'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Lists reports.
     */
    public function actionIndex() {

        $report = new Report;

        if (isset($_GET['Report']))
            $report->attributes = $_GET['Report'];

        $this->render('index', array('report' => $report));
    }

    public function actionManager($id) {
        _cs()->registerCssFile(_bu('css/gridview.css'));
        $typeCounts = array();

        $typeCounts = Report::getCountsForManager($id);

        $this->render('manager', array(
            'typeCounts' => $typeCounts,
            'manager' => Manager::Model()->findByPk($id)
        ));
    }

    public function actionView($id, $type) {
        _cs()->registerCoreScript('jquery.ui');
        AdminUtils::registerAdminJsFile('report');
        AdminUtils::registerAdminJsFile('ban');
        AdminUtils::registerAdminCssFile('jui/base/jquery-ui');
        AdminUtils::registerAdminCssFile('gridview');

        $criteria = new CDbCriteria;
        $criteria->with = array('reportReason');
        $criteria->condition = 'manager_id = :id';
        $criteria->params = array(':id' => $id);
        switch ($type) {
            case 'Username':
                $criteria->addInCondition('reportReason.reason_type', array(ReportReason::USERNAME));
                break;
            case 'Team Name':
                $criteria->addInCondition('reportReason.reason_type', array(ReportReason::TEAM_NAME));
                break;
            case 'Photo':
                $criteria->addInCondition('reportReason.reason_type', array(ReportReason::PHOTO));
                break;
            case 'Status':
                $criteria->addInCondition('reportReason.reason_type', array(ReportReason::STATUS));
                break;
            case 'Message':
                $criteria->addInCondition('reportReason.reason_type', array(ReportReason::MESSAGE));
                break;
            case 'Cheating':
                $criteria->addInCondition('reportReason.reason_type', array(ReportReason::CHEATING));
                break;
            case 'Other':
                $criteria->addInCondition('reportReason.reason_type', array(ReportReason::OTHER));
                break;
            default:
                break;
        }
        $criteria->order = 'date_created desc';
        $reports = Report::model()->findAll($criteria);

        if ($reports == null)
            $this->redirect(AdminUtils::aUrl('report/manager', array('id' => $id)));

        $this->render('view', array('reports' => $reports));
    }

    public function actionChangeTeamName() {
        if (isset($_POST['teamName'])) {
            if (Manager::changeAttribute($_POST['id'], 'name', $_POST['teamName'], 'update', 'managerTeam')) {
                Report::model()->deleteReport(ReportReason::TEAM_NAME, $_POST['id']);

                _user()->setFlash('success', 'User team name has been updated to <strong>' . $_POST['teamName'] . '</strong> and their reports have been deleted.');
            }
        }

        $this->redirect(AdminUtils::aUrl('report/manager', array('id' => $_POST['id'])));
    }

    public function actionDeleteStatus($id) {
        if (Manager::changeAttribute($id, 'line', null, 'delete', 'profile')) {
            Report::model()->deleteReport(ReportReason::STATUS, $id);

            _user()->setFlash('success', 'User\'s status and reports have been deleted.');
        }

        $this->redirect(AdminUtils::aUrl('report/manager', array('id' => $id)));
    }

    public function actionDeletePhoto($id) {
        $photo = Manager::model()->findByPk($id)->profile->photo;
        if ($m = Manager::changeAttribute($id, 'photo', null, 'delete', 'profile')) {
            if ($photo)
                unlink('images/manager_photos/' . $photo);
            Report::model()->deleteReport(ReportReason::PHOTO, $id);

            _user()->setFlash('success', 'User\'s photo and reports have been deleted.');
        }

        $this->redirect(AdminUtils::aUrl('report/manager', array('id' => $id)));
    }

    public function actionDeleteMessage($id, $rid) {
        $commentReport = CommentReported::model()->find('report_id = :id', array(':id' => $rid));
        if ($commentReport) {
            $comment = $commentReport->comment;
            $sid = $comment->id;
            $discussion = CategoryDiscussion::model()->getCommentDiscussion($comment->id);
            if ($discussion) {
                $pm = PMThread::model()->find('discussion_id = :did', array(':did' => $discussion->id));
                if ($pm)
                    $pm->delete();
                $discussion->visible = false;
                $discussion->save(false, array('visible'));
            } else {
                $comment->visible = false;
                $comment->save(false, array('visible'));
            }
        }
        Report::model()->deleteReport(ReportReason::MESSAGE, $id, $sid);
        _user()->setFlash('success', 'All reports have been removed and the message has become invisible.');
        $this->redirect(AdminUtils::aUrl('report/manager', array('id' => $id)));
    }

    public function actionMessageDetails($id, $mid) {
        $reports = Report::model()->findAll('id IN (select report_id from mod_forum_comments_reported where comment_id = :id)', array(':id' => $id));
        $message = Comment::model()->findByPk($id);
        if ($message) {
            $title = 'View discussion >>';
            $content = $message->content;
            $discussion = $message->discussion_id;
        }
        $this->renderPartial('_messageDetails', array('reports' => $reports, 'manager_id' => $mid, 'mid' => $id, 'minfo' => array('title' => $title, 'content' => $content, 'discussion' => $discussion)));
        return;
    }

    public function actionDelete($type, $id, $sid=false) {
        Report::model()->deleteReport($type, $id, $sid);
        $reason = ReportReason::getType($type);

        if (!_user()->hasFlash('success'))
            _user()->setFlash('success', "Reports for {$reason} have been deleted.");

        $this->redirect(AdminUtils::aUrl('report/manager', array('id' => $id)));
    }

}

protected/modules/admin/views/report/_banForm.php
<div class="form stables">
<?php echo CHtml::form(AdminUtils::aUrl('manager/ban'),'post'); ?>

    You are banning user: <b><?php echo $manager->username; ?></b>
    
    <?php echo CHtml::hiddenField('id',$manager->id); ?>
    
    <div class="row">
        <?php echo CHtml::label('Ban Reason','reason'); ?>
        <?php echo CHtml::dropDownList('reason','',CHtml::listData(ReportReason::model()->reportTypes()->findAll(),'id','reason')); ?>
    </div>

    <div class="row">
        <?php echo CHtml::label('Ban Duration in days','duration'); ?>
        <?php echo CHtml::textField('duration'); ?>
    </div>

    <div class="row">
        <?php echo CHtml::label('Notes','notes'); ?>
        <?php echo CHtml::textArea('notes',$manager->notes,array('cols'=>'70','rows'=>'15')); ?>
    </div>

    <div class="row buttons">
        <?php echo CHtml::submitButton('Ban'); ?>
    </div>

<?php echo CHtml::endForm(); ?>
</div>

protected/modules/admin/views/report/_cheating.php
<div class="reports">
    <div class="user">
        <?php echo $manager->username; ?>
    </div>
    <div class="options">
        <span class="delete"><?php echo CHtml::link('Delete reports', AdminUtils::aUrl('report/delete', array('type' => ReportReason::CHEATING,'id' => $manager->id))); ?></span>
        <span class="ban"><?php echo CHtml::link('Ban user', AdminUtils::aUrl('manager/ban', array('id' => $manager->id)),array('id' => 'banLink')); ?></span>
    </div>
    <div class="grid-view">
        <table class="items">
            <thead>
                <tr>
                    <th width="15%">Action</th>
                    <th width="15%">Reporter</th>
                    <th width="35%">Reason</th>
                    <th width="20%">Details</th>
                    <th width="15%">Date reported</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($reports as $report) : ?>
                    <tr>
                        <td><?php echo $report->reportReason->reportActions[0]->action; ?></td>
                        <td><?php echo $report->reporter->username; ?></td>
                        <td><?php echo $report->reportReason->reason; ?></td>
                        <td><?php echo $report->comment; ?></td>
                        <td><?php echo Utils::date($report->date_created); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<div class="ban-dialog">
    <?php $this->renderPartial('_banForm',array('manager'=>$manager)); ?>
</div>

protected/modules/admin/views/report/_messageDetails.php
<div class="title">
    <?php if ($minfo['discussion']) : ?>
        <span>
    <?php echo PMThread::model()->exists('discussion_id = :did', array(':did' => $minfo['discussion'])) ? 
        CHtml::link($minfo['title'], AdminUtils::aUrl('manager/thread', array('id' => $minfo['discussion'])), array('target' => '_blank')) :
        CHtml::link($minfo['title'], AdminUtils::aUrl('forum/show', array('discussion' => $minfo['discussion'])), array('target' => '_blank')); ?></span>
    <?php else : ?>
        <span><?php echo $minfo['title']; ?></span>
    <?php endif; ?>
</div>
<div class="info">
    <?php echo $minfo['content']; ?>
</div>
<div class="options">
    <?php if (!PMThread::model()->exists('discussion_id = :did', array(':did' => $minfo['discussion']))) : ?>
        <span class="remove"><?php echo CHtml::link('Hide this comment', AdminUtils::aUrl('report/deleteMessage', array('id' => $manager_id, 'rid' => $reports[0]->id))); ?></span>
    <?php endif; ?>
    <span class="delete"><?php
    echo CHtml::link('Delete reports', AdminUtils::aUrl('report/delete', array(
            'type' => ReportReason::MESSAGE,
            'id' => $manager_id,
            'sid' => $mid,
        )));
    ?></span>
</div>
<div class="grid-view">
    <?php echo count($reports); ?> reports
    <table class="items">
        <thead>
            <tr>
                <th>Reporter</th>
                <th>Report reason</th>
                <th>Details</th>
        </thead>
        <tbody>
            <?php foreach ($reports as $report) : ?>
                <tr>
                    <td><?php echo $report->reporter->username; ?></td>
                    <td><?php echo $report->reportReason->reason; ?></td>
                    <td><?php echo $report->comment; ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

protected/modules/admin/views/report/_other.php
<div class="reports">
    <div class="user">
        <?php echo $manager->username; ?>
    </div>
    <div class="options">
        <span class="delete"><?php echo CHtml::link('Delete reports', AdminUtils::aUrl('report/delete', array('type' => ReportReason::OTHER,'id' => $manager->id))); ?></span>
        <span class="ban"><?php echo CHtml::link('Ban user', AdminUtils::aUrl('manager/ban', array('id' => $manager->id)),array('id' => 'banLink')); ?></span>
    </div>
    <div class="grid-view">
        <table class="items">
            <thead>
                <tr>
                    <th width="15%">Action</th>
                    <th width="15%">Reporter</th>
                    <th width="35%">Reason</th>
                    <th width="20%">Details</th>
                    <th width="15%">Date reported</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($reports as $report) : ?>
                    <tr>
                        <td><?php echo $report->reportReason->reportActions[0]->action; ?></td>
                        <td><?php echo $report->reporter->username; ?></td>
                        <td><?php echo $report->reportReason->reason; ?></td>
                        <td><?php echo $report->comment; ?></td>
                        <td><?php echo Utils::date($report->date_created); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<div class="ban-dialog">
    <?php $this->renderPartial('_banForm',array('manager'=>$manager)); ?>
</div>

protected/modules/admin/views/report/_photo.php
<div class="reports">
    <div class="user">
        <?php echo $manager->username; ?>
    </div>
    <div class="info">
        <?php echo $manager->profile->photo ? CHtml::image(AdminUtils::adminImageUrl('manager_photos/' . $manager->profile->photo)) : 'No image'; ?>
    </div>
    <div class="options">
        <span class="remove"><?php echo CHtml::link('Remove photo', AdminUtils::aUrl('report/deletePhoto', array('id' => $manager->id))); ?></span>
        <span class="delete"><?php echo CHtml::link('Delete reports', AdminUtils::aUrl('report/delete', array('type' => ReportReason::PHOTO,'id' => $manager->id))); ?></span>
        <span class="ban"><?php echo CHtml::link('Ban user', AdminUtils::aUrl('manager/ban', array('id' => $manager->id)),array('id' => 'banLink')); ?></span>
    </div>
    <div class="grid-view">
        <table class="items">
            <thead>
                <tr>
                    <th width="30%">Reporter</th>
                    <th width="40%">Details</th>
                    <th width="30%">Date reported</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($reports as $report) : ?>
                    <tr>
                        <td><?php echo $report->reporter->username; ?></td>
                        <td><?php echo $report->comment; ?></td>
                        <td><?php echo Utils::date($report->date_created); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<div class="ban-dialog">
    <?php $this->renderPartial('_banForm',array('manager'=>$manager)); ?>
</div>

protected/modules/admin/views/report/_status.php
<div class="reports">
    <div class="user">
        <?php echo $manager->username; ?>
    </div>
    <div class="info">
        <?php echo $manager->profile->line != null ? $manager->profile->line : $manager->username.' has not entered a status.'; ?>
    </div>
    <div class="options">
        <span class="remove"><?php echo CHtml::link('Remove status', AdminUtils::aUrl('report/deleteStatus', array('id' => $manager->id))); ?></span>
        <span class="delete"><?php echo CHtml::link('Delete reports', AdminUtils::aUrl('report/delete', array('type' => ReportReason::STATUS,'id' => $manager->id))); ?></span>
        <span class="ban"><?php echo CHtml::link('Ban user', AdminUtils::aUrl('manager/ban', array('id' => $manager->id)),array('id' => 'banLink')); ?></span>
    </div>
    <div class="grid-view">
        <table class="items">
            <thead>
                <tr>
                    <th width="30%">Reporter</th>
                    <th width="40%">Details</th>
                    <th width="30%">Date reported</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($reports as $report) : ?>
                    <tr>
                        <td><?php echo $report->reporter->username; ?></td>
                        <td><?php echo $report->comment; ?></td>
                        <td><?php echo Utils::date($report->date_created); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<div class="ban-dialog">
    <?php $this->renderPartial('_banForm',array('manager'=>$manager)); ?>
</div>

protected/modules/admin/views/report/_teamName.php
<div class="reports">
    <div class="user">
        <?php echo $manager->username; ?>
    </div>
    <div class="info">
        <?php echo $manager->managerTeam->name; ?>
    </div>
    <div class="options">
        <div><?php echo CHtml::form(AdminUtils::aUrl('report/changeTeamName'),'post',array('id' => 'teamNameForm')); ?>
            <?php echo CHtml::textField('teamName', $manager->managerTeam->name); ?>
            <?php echo CHtml::hiddenField('id',$manager->id); ?>
            <?php echo CHtml::submitButton('Save'); ?>
        <?php echo CHtml::endForm(); ?>
        </div>
        <span class="delete"><?php echo CHtml::link('Delete reports', AdminUtils::aUrl('report/delete', array('type' => ReportReason::TEAM_NAME,'id' => $manager->id))); ?></span>
        <span class="ban"><?php echo CHtml::link('Ban user', AdminUtils::aUrl('manager/ban', array('id' => $manager->id)),array('id' => 'banLink')); ?></span>
    </div>
    <div class="grid-view">
        <table class="items">
            <thead>
                <tr>
                    <th width="30%">Reporter</th>
                    <th width="40%">Details</th>
                    <th width="30%">Date reported</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($reports as $report) : ?>
                    <tr>
                        <td><?php echo $report->reporter->username; ?></td>
                        <td><?php echo $report->comment; ?></td>
                        <td><?php echo Utils::date($report->date_created); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<div class="ban-dialog">
    <?php $this->renderPartial('_banForm',array('manager'=>$manager)); ?>
</div>

protected/modules/admin/views/report/_username.php
<div class="reports">
    <div class="user">
        <?php echo $manager->username; ?>
    </div>
    <div class="options">
        <span class="delete"><?php echo CHtml::link('Delete reports', AdminUtils::aUrl('report/delete', array('type' => ReportReason::USERNAME, 'id' => $manager->id))); ?></span>
        <span class="ban"><?php echo CHtml::link('Ban user', AdminUtils::aUrl('manager/ban', array('id' => $manager->id)),array('id' => 'banLink')); ?></span>
    </div>
    <div class="grid-view">
        <table class="items">
            <thead>
                <tr>
                    <th width="30%">Reporter</th>
                    <th width="40%">Details</th>
                    <th width="30%">Date reported</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($reports as $report) : ?>
                    <tr>
                        <td><?php echo $report->reporter->username; ?></td>
                        <td><?php echo $report->comment; ?></td>
                        <td><?php echo Utils::date($report->date_created); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<div class="ban-dialog">
    <?php $this->renderPartial('_banForm',array('manager'=>$manager)); ?>
</div>

protected/modules/admin/views/report/index.php
<?php
$this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'reports',
    'dataProvider' => $report->search(),
    'filter' => $report,
    'pager' => array('class' => 'CLinkPager', 'header' => ''),    'columns' => array(
        array(
            'header' => '',
            'value' => '$this->grid->dataProvider->pagination->currentPage*$this->grid->dataProvider->pagination->pageSize + $row+1',
        ),
        array(
            'type'=>'raw',
            'header' => 'Manager',
            'name' => 'reported',
            'value'=>'CHtml::link($data->reported,AdminUtils::aUrl(\'report/manager\', array(\'id\'=>$data->id)))',
        ),
        array(
            'header' => 'Reports',
            'name' => 'count',
            'filter'=>false,
            'htmlOptions'=>array('class'=>'tcenter')
        ),
    ),
));
?>

protected/modules/admin/views/report/manager.php
<div class="stables">
    <span class="success"><?php echo _user()->hasFlash('success') ? _user()->getFlash('success') : ''; ?></span>
    <span><?php echo _user()->hasFlash('failure') ? _user()->getFlash('failure') : ''; ?></span>
</div>
<div class="grid-view">
    Reports for <b><?php echo $manager->username; ?></b><br /><br />
    <table class="items" style="width: 50%;">
        <thead>
            <tr>
                <th>Type of report</th>
                <th>No of reports</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($typeCounts as $type => $count) : ?>
                <tr>
                    <td><a href="<?php echo $count ? AdminUtils::aUrl('report/view',array('id'=>$manager->id,'type'=>$type)) : '#'; ?>"><?php echo $type; ?></td>
                    <td class="center-align <?php echo ($count) ? 'red' : ''; ?>"><?php echo $count; ?></td>
                </tr>
            <?php endforeach; ?>
    </table>
</div>

<?php echo CHtml::link('&lt&ltBack',AdminUtils::aUrl('report/index')); ?>